<?php

namespace Infrastructure\Repositories\Directory;
use Core\Exceptions\ApplicationException;
use Doctrine\ORM\EntityManager;
use Infrastructure\Repositories\AbstractRepository;
use Domain\Contracts\Repository\Directory\BankAccountRepositoryContract;

use Domain\Entities\Business\Directory\BankAccounts;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BankAccountRepository extends AbstractRepository implements BankAccountRepositoryContract
{

    public function __construct(EntityManager $em, BankAccounts $entity)
    {

        parent::__construct($em, $entity);
    }


}
