<?php

namespace Infrastructure\Repositories\Directory;
use Core\Exceptions\ApplicationException;
use Doctrine\ORM\EntityManager;
use Illuminate\Http\UploadedFile;
use Infrastructure\Repositories\AbstractRepository;
use Domain\Contracts\Repository\Directory\BankRepositoryContract;
use Domain\Contracts\Repository\Directory\BankAccountRepositoryContract;
use Domain\Entities\Business\Directory\Bank;
use Illuminate\Support\Facades\Log;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class BankRepository extends AbstractRepository  implements BankRepositoryContract
{

    private BankAccountRepositoryContract $bankAccountRepository;

    public function __construct(EntityManager $em, Bank $entity,BankAccountRepositoryContract $bankAccountRepository)
    {
        $this->bankAccountRepository = $bankAccountRepository;
        parent::__construct($em, $entity);
    }


}


