<?php

namespace Infrastructure\Repositories\Directory;
use Doctrine\ORM\EntityManager;
use Infrastructure\Repositories\AbstractRepository;
use Domain\Contracts\Repository\Directory\PartnersBankAccountRepositoryContract;
use Domain\Entities\Business\Directory\PartnerBankAccounts;
use Doctrine\Common\Collections\Criteria;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class PartnersBankAccountRepository extends AbstractRepository implements PartnersBankAccountRepositoryContract
{

    public function __construct(EntityManager $em, PartnerBankAccounts $entity)
    {
        parent::__construct($em, $entity);
    }

}
