<?php

namespace Infrastructure\Repositories\Directory;
use Doctrine\ORM\EntityManager;
use Infrastructure\Repositories\AbstractRepository;
use Domain\Contracts\Repository\Directory\ProfessionRepositoryContract;
use Domain\Entities\Business\Directory\Profession;
use Doctrine\Common\Collections\Criteria;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ProfessionRepository extends AbstractRepository implements ProfessionRepositoryContract
{

    public function __construct(EntityManager $em, Profession $entity)
    {
        parent::__construct($em, $entity);
    }

}
