<?php

namespace Infrastructure\Repositories\Directory;
use Core\Exceptions\ApplicationException;
use Doctrine\ORM\EntityManager;
use Infrastructure\Repositories\AbstractRepository;
use Domain\Contracts\Repository\Directory\RecipientRepositoryContract;

use Domain\Entities\Business\Directory\Recipient;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipientRepository extends AbstractRepository implements RecipientRepositoryContract
{

    public function __construct(EntityManager $em, Recipient $entity)
    {

        parent::__construct($em, $entity);
    }


}
