<?php

namespace Infrastructure\Repositories\Business;
use Doctrine\ORM\EntityManager;
use Infrastructure\Repositories\AbstractRepository;
use Domain\Contracts\Repository\Business\CompanyRepositoryContracts;
use Domain\Entities\Business\Company\Company;
use Gedmo\Mapping\Annotation as Gedmo;
use Illuminate\Support\Facades\Log;
/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends AbstractRepository implements CompanyRepositoryContracts
{
    public function __construct(EntityManager $em, Company $entity)
    {
        parent::__construct($em, $entity);
    }
}
