<?php

namespace Tests;

use Laravel\Lumen\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    /**
     * Creates the application.
     *
     * @return \Laravel\Lumen\Application
     */
    public function createApplication()
    {

        return require __DIR__.'/../Application/Lumen/bootstrap/app.php';
    }

    protected function setUp(): void
    {
        echo "TestAccountAuth:setUp() \r\n";
        $this->assertTrue(true);
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
