<?php

namespace Tests;

class TestAccountAuth extends TestCase
{
    protected function setUp(): void
    {
        echo "TestAccountAuth:setUp() \r\n";
        $this->assertTrue(true);
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    public function it_tests_something()
    {
        echo "TestAccountAuth:it_tests_something() \r\n";
    }
}
