kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-data-redis-stage-master-0
  labels:
    type: local
    app: redis
    component: master
    heritage: Tiller
    release: redis-stage
    role: master
  namespace: stage
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/stage/redis-master/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data-redis-stage-master-0
  labels:
    type: local
    app: redis
    component: master
    heritage: Tiller
    release: redis-stage
    role: master
  namespace: stage
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-data-redis-stage-slave-0
  labels:
    type: local
    app: redis
    component: slave
    heritage: Tiller
    release: redis-stage
    role: slave
  namespace: stage
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/stage/redis-slave/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data-redis-stage-slave-0
  labels:
    type: local
    app: redis
    component: slave
    heritage: Tiller
    release: redis-stage
    role: slave
  namespace: stage
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
