<?php

namespace Infrastructure\Repositories\News;
use Domain\Entities\News\Comments;
use Doctrine\ORM\EntityManager;
use Infrastructure\Repositories\AbstractRepository;
use Domain\Contracts\Repository\NewsCommentsRepositoryContracts;
/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends AbstractRepository implements NewsCommentsRepositoryContracts
{
    protected $em;


    public function __construct(EntityManager $em, Comments $entity)
    {
        parent::__construct($em, $entity);
    }
    
    public function add($news,$data) 
    {
        $comments= $this->create($data);
      
        $comments->setNews($news);
        $this->update($news,$comments);
        dd($comments);

    }
}
