<?php

namespace Infrastructure\Repositories\News;
use Domain\Entities\News\News;
use Domain\Entities\News\Comments;

use Doctrine\ORM\EntityManager;
use Infrastructure\Repositories\AbstractRepository;
use Domain\Contracts\Repository\NewsRepositoryContracts;
use Auth;
/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends AbstractRepository implements NewsRepositoryContracts
{
    
    protected $em;
    protected $entityName;
    protected $entityNamespace;
    protected CommentsRepository $comments;

    public function __construct(EntityManager $em, News $entity, CommentsRepository $comments)
    {
        $this->comments = $comments;
        parent::__construct($em, $entity);
    }

    public function findAllCommnets(int $idNews)
    {
        return $this->findOne($idNews);  
        # code...
    }
    #todo Наименование переменых привестив соответствие 
    public function createCommnets($news, $arrKeyValue)
    {
        
        $news = $this->findOne($news);
        $commnets = $this->comments->loadNew($arrKeyValue);
        $commnets = $commnets->setNews($news);
        //$comments = $commnets->setAutorId(Auth::user());
        
        $this->save($commnets);
        return $news;        

        
    }
  
}
