<?php

namespace Infrastructure\Repositories\Reporting;
use DateTimeImmutable;
use Doctrine\ORM\EntityManager;
use Domain\Entities\Business\Directory\Partner;
use Infrastructure\Repositories\AbstractRepository;
use Domain\Entities\Business\Master\Brigade;
use Domain\Entities\Business\Payments\Invoice;
use Doctrine\Common\Collections\Criteria;
use Domain\Contracts\Repository\Reporting\BrigadesReportingRepositoryContract;
/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class BrigadesReportingRepository implements BrigadesReportingRepositoryContract
{

    private Invoice $invoice;
    private Partner $partner;

    public function __construct(EntityManager $em)
    {

    }

    public function index(DateTimeImmutable $stDate, DateTimeImmutable $endDate, Brigade $brigade = null, $options=[]) {

    }

    public function findByUuid($uuid) {

    }


}
