<?php

namespace Infrastructure\Repositories\Services;
use Domain\Entities\Services\Files;
use Infrastructure\Repositories\AbstractRepository;
use Domain\Contracts\Repository\Services\FileRepositoryContracts;
use Doctrine\ORM\EntityManager;
/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends AbstractRepository implements FileRepositoryContracts
{

    protected $em;
    protected $entityName;
    protected $entityNamespace;


    public function __construct(EntityManager $em, Files $entity)
    {
        $this->em = $em;
        $this->entity = $entity;
        parent::__construct($em, $entity);
    }

    public function create($arr) {
        parent::__construct($this->em, $this->entity);
        return parent::create($arr);

    }


    public function save($entity)
    {
        $this->em->persist($entity);
        $this->em->flush($entity);
        return $entity;
        //return parent::save($entity); // TODO: Change the autogenerated stub
    }

    public function getFileHash($hash){

        return parent::findBy(['hash'=>$hash]);
    }
}
