<?php

namespace Infrastructure\Repositories\Services;
use Domain\Entities\Services\Notification;
use Infrastructure\Repositories\AbstractRepository;
use Doctrine\ORM\EntityManager;
use Domain\Contracts\Repository\Services\NotificationRepositoryContracts;
use Domain\Contracts\Repository\Services\FileRepositoryContracts;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends AbstractRepository implements NotificationRepositoryContracts
{

    protected $em;
    private  FileRepositoryContracts $fileRepository;
    public function __construct(EntityManager $em, Notification $entity, FileRepositoryContracts $fileRepository)
    {
        $this->fileRepository =  $fileRepository;
        parent::__construct($em, $entity);
    }
}

