<?php

namespace Infrastructure\Repositories\Payments;
use DateTimeImmutable;
use Doctrine\ORM\EntityManager;
use Domain\Entities\Business\Directory\Partner;
use Domain\Entities\Business\Objects\Specification;
use Infrastructure\Repositories\AbstractRepository;
use Domain\Entities\Business\Payments\Invoice;
use Doctrine\Common\Collections\Criteria;
use Domain\Contracts\Repository\Payments\InvoicesRepositoryContract;
/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class InvoicesRepository extends AbstractRepository implements InvoicesRepositoryContract
{

    public function __construct(EntityManager $em, Invoice $entity)
    {
        parent::__construct($em, $entity);
    }

    public function newInvoice(Partner $partner, DateTimeImmutable $date, $type, float $amount): Invoice
    {
        $invoiceData = [
            "partner"=>$partner,
            "date"=>$date,
            "amount"=>$amount
        ];
        return $this->create($invoiceData);

    }

    public function invoicesSpecification(Specification $specification) {

        return $this->findAllBy(['specification'=>$specification]);
    }



}
