<?php

namespace Infrastructure\Repositories\Account;
use Doctrine\ORM\EntityManager;
use Infrastructure\Repositories\AbstractRepository;
use Domain\Contracts\Repository\RolesRepositoryContracts;
use Domain\Entities\Subscriber\Roles;

/**
 * RolesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolesRepository extends AbstractRepository implements RolesRepositoryContracts
{
    public function __construct(EntityManager $em, Roles $entity)
    {
        parent::__construct($em, $entity);
    }



}
