<?php

namespace Infrastructure\Repositories\Crm;
use Doctrine\ORM\EntityManager;
use Infrastructure\Repositories\AbstractRepository;
use Domain\Contracts\Repository\Crm\ObjectsRepositoryContracts;
use Doctrine\Common\Collections\Criteria;

use Domain\Entities\Business\Objects\Objects;
use Infrastructure\Repositories\Account\AccountsRepository;
use Infrastructure\Repositories\Services\FileRepository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectsRepository extends AbstractRepository implements ObjectsRepositoryContracts
{
    private AccountsRepository $accountsRepository;
    private FileRepository $fileRepository;
    public function __construct(
        EntityManager $em,
        Objects $entity,
        AccountsRepository $accountsRepository,
        FileRepository $fileRepository
    ){

        $this->accountsRepository = $accountsRepository;
        $this->fileRepository = $fileRepository;
        parent::__construct($em, $entity);
    }

    public function countProjects($objectId)
    {
        $criteria = Criteria::create()
            ->where(Criteria::expr()->eq("delete", false));
        $object = $this->find($objectId);

        return $object->getProjects()->matching($criteria)->count();;
    }
}
