<?php

namespace Infrastructure\Repositories\Crm;
use Doctrine\ORM\EntityManager;
use Infrastructure\Repositories\AbstractRepository;
use Domain\Contracts\Repository\Crm\SpecificationTypeWorksRepositoryContracts;
use Domain\Entities\Business\Objects\SpecificationTypeWorks;
/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecificationTypeWorksRepository extends AbstractRepository implements SpecificationTypeWorksRepositoryContracts
{
    public function __construct(EntityManager $em, SpecificationTypeWorks $entity)
    {
        parent::__construct($em, $entity);
    }
}
