<?php

namespace Infrastructure\Repositories\Crm;
use Doctrine\ORM\EntityManager;
use Infrastructure\Repositories\AbstractRepository;
use Domain\Contracts\Repository\Crm\SpecificationResourcesRepositoryContracts;

use Domain\Entities\Business\Objects\SpecificationResources;
use Domain\Entities\Business\Objects\Specification;
/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecificationResourcesRepository extends AbstractRepository implements  SpecificationResourcesRepositoryContracts
{
    private Specification $specification;
    public function __construct(EntityManager $em, SpecificationResources $entity)
    {

        parent::__construct($em, $entity);
    }
}
