<?php

namespace Infrastructure\Repositories\Crm;
use Doctrine\ORM\EntityManager;
use Infrastructure\Repositories\AbstractRepository;
use Domain\Contracts\Repository\Crm\SpecificationRequisitionRepositoryContracts;

use Domain\Entities\Business\Master\Requisition;
use Domain\Entities\Business\Objects\Specification;
use Infrastructure\Repositories\Crm\SpecificationMaterialRepository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecificationRequisitionRepository extends AbstractRepository implements  SpecificationRequisitionRepositoryContracts
{
    private Specification $specification;
    private SpecificationMaterialRepository $specificationMaterial;

    public function __construct(EntityManager $em, Requisition $entity, Specification $specification, SpecificationMaterialRepository $specificationMaterial)
    {
        $this->specification = $specification;
        $this->specificationMaterial = $specificationMaterial;
        parent::__construct($em, $entity);
    }

}
