<?php

namespace Infrastructure\Repositories\Utils;
use Infrastructure\Repositories\AbstractRepository;
use Domain\Contracts\Repository\Utils\UnitsRepositoryContracts;
use Doctrine\ORM\EntityManager;
use Domain\Entities\Utils\Units;
/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitsRepository extends AbstractRepository implements UnitsRepositoryContracts
{
    
    protected $em;
    protected $entityName;


    public function __construct(EntityManager $em, Units $entity)
    {
        $this->em = $em;
        //$this->entity = $entity;
        parent::__construct($em, $entity);
    }

    public function findAllBy($arrKeyValue, $arrOrderBy = null) {
        $units = parent::findAllBy($arrKeyValue);
        return $units;
        
    }

    public function findCode($code) {
        return parent::findOneBy(['code'=>$code]);
    }

    public function findAll() {
        return $this->em->getRepository(get_class($this->entity))->findAll();
        //return parent::findAll();
    }



}
