Domain\Entities\Business\Document\Workflow:
  properties:
    id:
      exclude: true
    delete:
      exclude: true
    autorId:
      exclude: true
    active:
      exclude: true
    company:
      exclude: true
    tasks:
      exclude: true
    autor:
      exclude: true
      accessor:
        getter: getAutor
    deletedAt:
      exclude: true
    createdAt:
      exclude: true
    updatedAt:
      exclude: true
  virtual_properties:
    getId:
      name: uuid
      serialized_name: id
      type: string


