Domain\Entities\Services\Notification:
  properties:
    id:
      exclude: true
    delete:
      exclude: true
  virtual_properties:
    getId:
      name: uuid
      serialized_name: id
      type: string

