#Компании работающие в CRM
Domain\Entities\Business\Directory\Partner:
  properties:
    id:
      exclude: true
    delete:
      exclude: true
    autorId:
      exclude: true
    active:
      exclude: true
    company:
      exclude: true
    autor:
      exclude: true
    parent:
      exclude: false
    children:
      exclude: true
    invoices:
      exclude: true
    deletedAt:
      exclude: true
    updatedAt:
      exclude: true
    requisitionInvoice:
      exclude: true
    contracts:
      exclude: true
  virtual_properties:
    getId:
      name: uuid
      serialized_name: id
      type: uuid

