Domain\Entities\Business\Master\Brigade:
  properties:
    id:
      exclude: true
    delete:
      exclude: true
    autorId:
      exclude: true
    active:
      exclude: true
    company:
      exclude: true
    timesheet:
      exclude: true
    autor:
      exclude: true
      accessor:
        getter: getAutor
    brigade_pay:
      exclude: true
    deletedAt:
      exclude: true
    updatedAt:
      exclude: true
    workpeoples:
      exclude: false
    brigadeSpecification:
      exclude: true
  virtual_properties:
    getId:
      name: uuid
      serialized_name: id
      type: string
