#Справочник типы/виды работ
Domain\Entities\Business\Directory\TypeWorks:
  type: entity
  table: typeworks
  id:
    id:
      type: uuid
      nullable: false
      options:
        unsigned: true
      id: false
      generator:
        strategy: CUSTOM
      customIdGenerator:
        class: Ramsey\Uuid\Doctrine\UuidV7Generator
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false
  fields:
    name:
      type: string
      nullable: false
      options:
        unsigned: false
      column: name
    fullname:
      type: text
      nullable: true
      options:
        unsigned: false
      column: fullname
    quantity:
      type: float
      nullable: true
      column: quantity
    code:
      type: string
      nullable: true
      column: code
    units:
      type: string
      nullable: true
      column: units
    price:
      type: float
      nullable: true
      column: price
    sysid:
      type: integer
      nullable: true
      column: sysid
    category:
      type: string
      nullable: true
      column: category
    spcode:
      type: string
      nullable: true
      column: spcode
    nrcode:
      type: string
      nullable: true
      column: nrcode
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: true
      column: updated_at
    autorId:
      type: uuid
      nullable: true
      column: autor_uuid
    active:
      type: boolean
      nullable: true
      column: active
    delete:
      type: boolean
      nullable: true
      column: delete
      options:
        default: false
    deletedAt:
      type: datetime
      nullable: true
      column: deleted_at
      options:
        default: null
