Domain\Entities\Business\Objects\Contacts:
  type: entity
  table: contacts
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false
  fields:
    surname:
      type: string
      nullable: false
      column: surname
    name:
      type: string
      nullable: true
      column: name
    patronymic:
      type: string
      nullable: true
      unique: false
      column: patronymic
    fullname:
      type: string
      nullable: true
      column: fullname
    phone:
      type: string
      nullable: true
      column: phone
    email:
      type: text
      nullable: true
      column: email
    employee:
      type: text
      nullable: true
      column: employee
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: true
      column: updated_at
    autorId:
      type: uuid
      nullable: true
      column: autor_uuid
    active:
      type: boolean
      nullable: true
      column: active
    delete:
      type: boolean
      nullable: true
      column: delete
      options:
        default: false
    deletedAt:
      type: datetime
      nullable: true
      column: deleted_at
  manyToMany:
    objects:
      targetEntity: Domain\Entities\Business\Objects\Objects
      inversedBy: contacts
