Domain\Entities\Business\Company\Stock:
  type: entity
  table: stock
  id:
    id:
      type: uuid
      nullable: false
      options:
        unsigned: true
      id: false
      generator:
        strategy: CUSTOM
      customIdGenerator:
        class: Ramsey\Uuid\Doctrine\UuidV7Generator
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false
  fields:
    name:
      type: string
      nullable: false
      options:
        unsigned: false
      column: name
    fullname:
      type: text
      nullable: true
      options:
        unsigned: false
      column: fullname
    address:
      type: text
      nullable: true
      options:
        unsigned: false
      column: address
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: true
      column: updated_at
    active:
      type: boolean
      nullable: true
      column: active
    delete:
      type: boolean
      nullable: true
      column: delete
      options:
        default: false
    deletedAt:
      type: datetime
      nullable: true
      column: deleted_at
      options:
        default: null
  manyToOne:
    company:
      targetEntity: Domain\Entities\Business\Company\Company
      joinColumn:
        name: company_id
        referencedColumnName: id
    autor:
      targetEntity: Domain\Entities\Subscriber\Account
      joinColumn:
        name: autor_id
        referencedColumnName: id
  oneToOne:
    specification:
      targetEntity: Domain\Entities\Business\Objects\Specification
  oneToMany:
    requisitionInvoice:
      targetEntity: Domain\Entities\Business\Document\Requisition\Invoice
      mappedBy: stock
