Domain\Entities\Business\Directory\Price:
  type: entity
  table: price
  id:
    id:
      type: uuid
      nullable: false
      options:
        unsigned: true
      id: false
      generator:
        strategy: CUSTOM
      customIdGenerator:
        class: Ramsey\Uuid\Doctrine\UuidV7Generator
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false
  fields:
    total:
      type: float
      nullable: false
      options:
        unsigned: false
      column: total
    autorId:
      type: uuid
      nullable: true
      column: autor_uuid
    active:
      type: boolean
      nullable: true
      column: active
      options:
        default: true
    delete:
      type: boolean
      nullable: true
      column: delete
      options:
        default: false
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: true
      column: updated_at
    deletedAt:
      type: datetime
      nullable: true
      column: deleted_at
      options:
        default: null
  manyToOne:
    currency:
      targetEntity: Domain\Entities\Utils\Currency
      inversedBy: price
