#Запрос стоимостиматериала
Domain\Entities\Business\Objects\Specification\Material\Calculation:
  type: entity
  table: specification_material_calculation
  id:
    id:
      type: uuid
      nullable: false
      options:
        unsigned: true
      id: false
      generator:
        strategy: CUSTOM
      customIdGenerator:
        class: Ramsey\Uuid\Doctrine\UuidV7Generator
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false
  fields:
    amount:
      type: float
      nullable: false
      column: amount
    fixed:
      type: boolean
      nullable: true
      column: fixed
      options:
        default: false
    active:
      type: boolean
      nullable: true
      column: active
      options:
        default: true
    description:
      type: text
      nullable: true
      column: description
    draft:
      type: boolean
      nullable: true
      column: draft
      options:
        default: true
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: true
      column: updated_at
    deletedAt:
      type: datetime
      nullable: true
      column: deleted_at
  manyToOne:
    company:
      targetEntity: Domain\Entities\Business\Company\Company
      joinColumn:
        name: company_id
        referencedColumnName: id
    autor:
      targetEntity: Domain\Entities\Subscriber\Account
      joinColumn:
        name: autor
        referencedColumnName: id

