Domain\Entities\Business\Document\BrigadeSpecification:
  type: entity
  table: brigade_specification
  id:
    id:
      type: uuid
      nullable: false
      options:
        unsigned: true
      id: false
      generator:
        strategy: CUSTOM
      customIdGenerator:
        class: Ramsey\Uuid\Doctrine\UuidV7Generator
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false
  fields:
    endAt:
      type: datetime
      nullable: false
      column: end_at
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: true
      column: updated_at
    deletedAt:
      type: datetime
      nullable: true
      column: deleted_at
    active:
      type: boolean
      nullable: true
      column: active
    delete:
      type: boolean
      nullable: true
      column: delete
      options:
        default: false
  manyToOne:
    company:
      targetEntity: Domain\Entities\Business\Company\Company
      inversedBy: brigadeSpecification
    brigade:
      targetEntity: Domain\Entities\Business\Master\Brigade
      inversedBy: brigadeSpecification

    autor:
      targetEntity: Domain\Entities\Subscriber\Account
      joinColumn:
        name: autor_id
        referencedColumnName: id
    specification:
      targetEntity: Domain\Entities\Business\Objects\Specification
      inversedBy: brigadeSpecification
      orderBy: { 'createdAt': 'DESC',  'name': 'ASC'}


