Domain\Entities\Business\Document\Requisition\Invoice:
  type: entity
  table: requisition_invoice
  id:
    id:
      type: uuid
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: CUSTOM
      customIdGenerator:
        class: Ramsey\Uuid\Doctrine\UuidV7Generator
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false
  fields:
    number:
      type: string
      nullable: false
      size: 30
      column: number
    index:
      type: integer
      size: 12
      nullable: false
      column: index
    status:
      type: string
      size: 10
      nullable: true
      column: status
    description:
      type: text
      nullable: true
      column: description
    active:
      type: boolean
      nullable: true
      column: active
    amount:
      type: float
      nullable: false
      column: amount
    deliveryAt:
      type: datetime
      nullable: false
      column: delivery_at
    createdAt:
      type: datetime
      nullable: true
      column: created_at
    updatedAt:
      type: datetime
      nullable: true
      column: updated_at
    deletedAt:
      type: datetime
      nullable: true
      column: deleted_at
      options:
        default: null
    archiveAt:
      type: datetime
      nullable: true
      column: archive_at
    fixed:
      type: boolean
      nullable: true
      column: fixed
      options:
        default: false

  manyToOne:
    company:
      targetEntity: Domain\Entities\Business\Company\Company
      joinColumn:
        name: company
        referencedColumnName: id
    autor:
      targetEntity: Domain\Entities\Subscriber\Account
      joinColumn:
        name: autor
        referencedColumnName: id
    requisition:
      targetEntity: Domain\Entities\Business\Master\Requisition
      inversedBy: invoices
    partner:
      targetEntity: Domain\Entities\Business\Directory\Partner
      inversedBy: requisitionInvoice
    specification:
      targetEntity: Domain\Entities\Business\Objects\Specification
      inversedBy: requisitionInvoice
      cascade: ["persist", "merge"]
    contract:
      targetEntity: Domain\Entities\Business\Document\Contracts
      inversedBy: invoices
    stock:
      targetEntity: Domain\Entities\Business\Company\Stock
      inversedBy: requisitionInvoice
  oneToMany:
    materials:
      targetEntity: Domain\Entities\Business\Document\Requisition\Invoice\Material
      mappedBy: requisitionInvoice
  manyToMany:
    files:
      targetEntity: Domain\Entities\Services\Files
      mappedBy: requisitionInvoice


