Domain\Entities\Subscriber\Roles:
  type: entity
  table: roles
  id:
    id:
      type: uuid
      nullable: false
      options:
        unsigned: true
      id: false
      generator:
        strategy: CUSTOM
      customIdGenerator:
        class: Ramsey\Uuid\Doctrine\UuidV7Generator
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false
  fields:
    name:
      type: string
      nullable: false
      unique: false
      options:
        unsigned: false
      column: name
    service:
      type: string
      nullable: true
      unique: false
      options:
        unsigned: false
      column: service
    access:
      type: array
      nullable: true
      column: access
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: true
      column: updated_at
    fixed:
      type: boolean
      nullable: true
      options:
        default: false
      column: fixed
    autorId:
      type: array
      nullable: true
      column: autor_id
    active:
      type: boolean
      nullable: true
      column: active
    deletedAt:
      type: datetime
      nullable: true
      column: deleted_at
  oneToMany:
    account:
      targetEntity: Domain\Entities\Subscriber\Account
      cascade: ["persist", "merge"]
      mappedBy: roles
  manyToOne:
    company:
      targetEntity: Domain\Entities\Business\Company\Company
      inversedBy: roles
