Domain\Entities\Business\Objects\Objects:
  type: entity
  table: objects
  id:
    id:
      type: uuid
      nullable: false
      options:
        unsigned: true
      id: false
      generator:
        strategy: CUSTOM
      customIdGenerator:
        class: Ramsey\Uuid\Doctrine\UuidV7Generator
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false
  fields:
    name:
      type: string
      nullable: false
      options:
        unsigned: false
      column: name
    address:
      type: text
      nullable: true
      options:
        unsigned: false
      column: address
    status:
      type: string
      nullable: true
      options:
        unsigned: false
      column: status
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: true
      column: updated_at
    autorId:
      type: uuid
      nullable: true
      column: autor_uuid
    active:
      type: boolean
      nullable: true
      column: active
    draft:
      type: boolean
      nullable: true
      column: draft
    delete:
      type: boolean
      nullable: true
      column: delete
      options:
        default: false
    deletedAt:
      type: datetime
      nullable: true
      column: deleted_at
    archiveAt:
      type: datetime
      nullable: true
      column: archive_at
  oneToMany:
    specification:
      targetEntity: Domain\Entities\Business\Objects\Specification
      mappedBy: object
  manyToOne:
    company:
      targetEntity: Domain\Entities\Business\Company\Company
      inversedBy: objects
    autor:
      targetEntity: Domain\Entities\Subscriber\Account
      joinColumn:
        name: autor
        referencedColumnName: id
  manyToMany:
    contacts:
      targetEntity: Domain\Entities\Business\Objects\Contacts
      mappedBy: objects
    files:
      targetEntity: Domain\Entities\Services\Files
      inversedBy: objects
    accounts:
      targetEntity: Domain\Entities\Subscriber\Account
      mappedBy: objects
    responsibles:
      targetEntity: Domain\Entities\Subscriber\Account
      joinTable:
        name: object_responsible
        joinColumns:
          object_id:
            referencedColumnName: id
        inverseJoinColumns:
          account_id:
            referencedColumnName: id

