#Компании работающие в CRM
Domain\Entities\Business\Directory\Partner:
  type: entity
  table: partner
  id:
    id:
      type: uuid
      nullable: false
      options:
        unsigned: true
      id: false
      generator:
        strategy: CUSTOM
      customIdGenerator:
        class: Ramsey\Uuid\Doctrine\UuidV7Generator
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false
  fields:
    name:
      type: string
      nullable: false
      options:
        unsigned: false
      column: name
    fullname:
      type: text
      nullable: true
      options:
        unsigned: false
      column: full_name
    address:
      type: text
      nullable: true
      column: address
    type:
      type: string
      nullable: true
      column: type
    ogrnDate:
      type: bigint
      nullable: true
      column: ogrn_date
    ogrn:
      type: bigint
      nullable: true
      column: ogrn
    okpo:
      type: bigint
      nullable: true
      column: okpo
    nds:
      type: boolean
      nullable: true
      column: use_nds
    oktmo:
      type: bigint
      nullable: true
      column: oktmo
    okogu:
      type: bigint
      nullable: true
      column: okogu
    inn:
      type: bigint
      nullable: true
      column: inn
    kpp:
      type: bigint
      nullable: true
      column: kpp
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: true
      column: updated_at
    autorId:
      type: uuid
      nullable: true
      column: autor_uuid
    active:
      type: boolean
      nullable: true
      column: active
      options:
        default: true
    delete:
      type: boolean
      nullable: true
      column: delete
      options:
        default: false
    isGroup:
      type: boolean
      nullable: true
      options:
        default: false
      column: isGroup
    deletedAt:
      type: datetime
      nullable: true
      column: deleted_at
      options:
        default: null
  manyToOne:
    company:
      targetEntity: Domain\Entities\Business\Company\Company
      inversedBy: partner
    parent:
      targetEntity: Domain\Entities\Business\Directory\Partner
      inversedBy: children
    autor:
      targetEntity: Domain\Entities\Subscriber\Account
      joinColumn:
        name: autor
        referencedColumnName: id
  oneToMany:
    bankAccounts:
      targetEntity: Domain\Entities\Business\Directory\PartnerBankAccounts
      mappedBy: partner
    children:
      targetEntity: Domain\Entities\Business\Directory\Partner
      orderBy: { 'name': 'ASC' }
      mappedBy: parent
      onDelete: CASCADE
    contracts:
      targetEntity: Domain\Entities\Business\Document\Contracts
      mappedBy: partner
    requisitionInvoice:
      targetEntity: Domain\Entities\Business\Document\Requisition\Invoice
      mappedBy: partner

