# Задание рабочего процесса
Domain\Entities\Business\Document\Tasks:
  type: entity
  table: workflow_tasks
  id:
    id:
      type: uuid
      nullable: false
      options:
        unsigned: true
      id: false
      generator:
        strategy: CUSTOM
      customIdGenerator:
        class: Ramsey\Uuid\Doctrine\UuidV7Generator
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false
  fields:
    index:
      type: integer
      nullable: false
      column: index
    title:
      type: string
      nullable: false
      column: title
    description:
      type: text
      nullable: false
      column: description
    startDate:
      type: datetime
      nullable: true
      column: start_date
    endDate:
      type: datetime
      nullable: false
      column: end_date
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: true
      column: updated_at
    status:
      type: string
      nullable: true
      column: status
    priority:
      type: integer
      size: 2
      nullable: true
      column: priority
    active:
      type: boolean
      nullable: true
      column: active
      options:
        default: true
    delete:
      type: boolean
      nullable: true
      column: delete
      options:
        default: false
    deletedAt:
      type: datetime
      nullable: true
      column: deleted_at
      options:
        default: null
    archiveAt:
      type: datetime
      nullable: true
      column: archive_at
  manyToOne:
    company:
      targetEntity: Domain\Entities\Business\Company\Company
      inversedBy: tasks
    workflow:
      targetEntity: Domain\Entities\Business\Document\Workflow
      inversedBy: tasks
    autor:
      targetEntity: Domain\Entities\Subscriber\Account
      joinColumn:
        name: autor
        referencedColumnName: id
  manyToMany:
    responsible:
      targetEntity: Domain\Entities\Subscriber\Account
      mappedBy: tasks
    files:
      targetEntity: Domain\Entities\Services\Files
      mappedBy: tasks






