<?php

namespace Infrastructure\Repositories\Document;
use Doctrine\ORM\EntityManager;
use Domain\Contracts\Repository\Document\RequisitionMaterialRepositoryContract;
use Domain\Entities\Business\Directory\Material;
use Domain\Entities\Business\Master\RequisitionMaterials;
use Infrastructure\Repositories\AbstractRepository;

/**
 * MaterialCalculation
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialRequisitionMaterialRepository extends AbstractRepository implements RequisitionMaterialRepositoryContract
{
    public function __construct(
        EntityManager $em,
        RequisitionMaterials $entity,
    ) {
        parent::__construct($em, $entity);
    }

    public function setMaterialRequisitionDirectory(RequisitionMaterials $material_requisition, Material $material_directory){
        $material_requisition->setDirectoryMaterial($material_directory);
        return $material_requisition;
    }

}
